### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by mmottl** [janestreet/incremental#1]
The following code snippet in the documentation section of the incremental interface file

```ocaml
let w = map2 y z ~f:(fun y z -> y - z)
```

should probably be:
```ocaml
let w = map2 (Var.watch y) z ~f:(fun y z -> y - z)
```

**Comment by trefis** [comment]
Good catch!
This will be fixed in the next release.

Thank you.

**Comment by trefis** [comment]
This was fixed indeed fixed in the following release, closing.
