### ISSUE TITLE
Link to API documentation on incremental website is broken

### ISSUE THREAD

**Issue by michaelboulton** [janestreet/incremental#12]
https://opensource.janestreet.com/incremental/

links to 

https://ocaml.janestreet.com/ocaml-core/latest/doc/incremental_kernel/Incremental_kernel/Incremental_intf/

which is giving a 404. It should probably link to

https://ocaml.janestreet.com/ocaml-core/latest/doc/incremental/Incremental__/Incremental_intf/index.html

**Comment by yminsky** [comment]
Fixed. Thanks!
