### ISSUE TITLE
Link to Umut Acar et. al.'s paper in the README is broken

### ISSUE THREAD

**Issue by yannham** [janestreet/incremental#13]
The link to Umut Acar et. al.'s paper on self adjusting computations (http://www.umut-acar.org/self-adjusting-computation) lands on a "page not found". As Umut seems to have quite a lot of papers on self adjusting computations on the same site I was not able to infer which one in particular the link should refer to.

**Comment by yannham** [comment]
(P.S: the same broken link also appears in [the blog post](https://blog.janestreet.com/introducing-incremental/))

**Comment by yminsky** [comment]
I reached out to Scare, who fixed the link on his side.
