### ISSUE TITLE
Performance Characteristics

### ISSUE THREAD

**Issue by w14** [janestreet/incremental#15]
The documentation gives no clue about the performance characteristics of the library. Are there rough, order-of-magnitude rules-of-thumb for how big is too big a computation graph for incremental?

**Comment by TyOverby** [comment]
There are no real rules-of-thumb for graph size.  The biggest dominating factor is usually "size of part of graph that needs to be recomputed", but still, no real guidance for "how big is too big" given that usually you're comparing it to recomputing things from scratch without any incrementalization

**Comment by w14** [comment]
It is already helpful which factor matters—the size of the graph that needs to be recomputed. Is that the number of nodes / operations in the computation?

I'm looking for basic characteristics: 

1. Do computations get run in parallel when they can?
2. For a billion sequential computations, it would be surprising if it took more than 10s and less than 0.1s. Can you give any hint about where it falls?
