### ISSUE TITLE
Link to documentation is broken

### ISSUE THREAD

**Issue by retnuh** [janestreet/incremental#8]
The README.org file points to `incremental_kernel/src/incremental_intf.ml` saying that it has "detailed documentation in of the library and how to use it".  However, the link is broken.

There is a `src/incremental_intf.ml` file but it is quite small and does not contain documentation.

I'm guessing it should point to `https://github.com/janestreet/incremental_kernel/blob/master/src/incremental_intf.ml`

**Comment by yminsky** [comment]
Fixed now.
